// src/lib/annuaires-content.ts
// Données initiales vérifiées (République du Congo), utilisées en repli si
// les collections Firestore correspondantes sont vides/inaccessibles.

import type { AnnuaireItem } from "@/types/annuaire";

export const initialUniversities: AnnuaireItem[] = [
  {
    id: "umng",
    name: "Université Marien Ngouabi (UMNG)",
    type: "Université Publique",
    city: "Brazzaville",
    address: "Brazzaville Centre, BP 69",
    faculties: [
      "Droit & Sciences Économiques",
      "Sciences et Techniques",
      "Lettres et Sciences Humaines",
      "Sciences de la Santé",
      "École Nationale Supérieure Polytechnique (ENSP)",
    ],
    phone: "+242 22 281 14 30",
    email: "contact@umng.cg",
    website: "https://www.umng.cg",
  },
  {
    id: "udeu",
    name: "Université Denis Sassou-Nguesso (UDSN)",
    type: "Université Publique",
    city: "Kintélé",
    address: "Kintélé, Banlieue Nord de Brazzaville",
    faculties: ["Institut Supérieur d'Architecture", "Institut des Sciences Géographiques", "Sciences Appliquées"],
    phone: "+242 06 600 00 00",
    email: "info@udsn.cg",
    website: "https://www.udsn.cg",
  },
  {
    id: "esgae",
    name: "ESGAE (École Supérieure de Gestion et d'Administration des Entreprises)",
    type: "Grande École Privée",
    city: "Brazzaville",
    address: "Moungali, Rue Kimbondo, Brazzaville",
    faculties: ["Finance & Comptabilité", "Management & RH", "Marketing & Communication", "Logistique & Transport"],
    phone: "+242 05 551 22 33",
    email: "contact@esgae.org",
    website: "https://esgae.org",
  },
  {
    id: "estb",
    name: "ESTB (École Supérieure de Technologie de Brazzaville & Pointe-Noire)",
    type: "Institut Supérieur",
    city: "Pointe-Noire",
    address: "Centre-ville, Pointe-Noire",
    faculties: ["Génie Informatique & Réseaux", "Télécommunications", "Électromécanique"],
    phone: "+242 06 900 11 22",
    email: "contact@estb-congo.com",
    website: "",
  },
  {
    id: "isg-pn",
    name: "Institut Supérieur de Gestion (ISG)",
    type: "Institut Supérieur",
    city: "Pointe-Noire",
    address: "Quartier OCH, Pointe-Noire",
    faculties: ["Commerce International", "Gestion des Entreprises", "Banque & Microfinance"],
    phone: "+242 05 612 34 56",
    email: "isg.pointenoire@gmail.com",
    website: "",
  },
];

export const initialCompanies: AnnuaireItem[] = [
  {
    id: "totalenergies",
    name: "TotalEnergies EP Congo",
    sector: "Énergie, Pétrole & Gaz",
    city: "Pointe-Noire",
    address: "Base Industrielle, Route de l'Aéroport, Pointe-Noire",
    description: "Acteur historique de l'exploration et de la production d'hydrocarbures en République du Congo.",
    phone: "+242 22 294 00 00",
    email: "recrutement.congo@totalenergies.com",
    website: "https://totalenergies.cg",
  },
  {
    id: "versalis",
    name: "Versalis International Congo (Groupe Eni)",
    sector: "Industrie Chimique & Pétrochimie",
    city: "Pointe-Noire",
    address: "Zone Litchendjili, Pointe-Noire",
    description: "Services et technologies chimiques spécialisées pour le secteur pétrolier et industriel.",
    phone: "+242 06 500 00 00",
    email: "recrutement@versalis.eni.com",
    website: "https://www.versalis.eni.com",
  },
  {
    id: "mtn-congo",
    name: "MTN Congo",
    sector: "Télécommunications & Numérique",
    city: "Brazzaville",
    address: "Boulevard Denis Sassou Nguesso, Centre-ville, Brazzaville",
    description: "Opérateur leader des télécommunications, réseau mobile et services Mobile Money en République du Congo.",
    phone: "+242 06 600 01 23",
    email: "careers.congo@mtn.com",
    website: "https://www.mtn.cg",
  },
  {
    id: "airtel-congo",
    name: "Airtel Congo",
    sector: "Télécommunications & Internet",
    city: "Brazzaville",
    address: "Avenue Amilcar Cabral, Brazzaville",
    description: "Fournisseur de solutions mobiles, internet 4G/fibre et services financiers Airtel Money.",
    phone: "+242 05 500 01 23",
    email: "rh@cg.airtel.com",
    website: "https://www.airtel.cg",
  },
  {
    id: "bralico",
    name: "BRALICO (Brasseries du Congo - Groupe Castel)",
    sector: "Agroalimentaire & Boissons",
    city: "Pointe-Noire",
    address: "Zone Portuaire, Pointe-Noire / Brazzaville",
    description: "Production et distribution de boissons de qualité, bières et sodas.",
    phone: "+242 22 294 15 20",
    email: "rh.bralico@castel-afrique.com",
    website: "https://www.castel-afrique.com",
  },
  {
    id: "agl-congo",
    name: "AGL Congo (Africa Global Logistics)",
    sector: "Transport, Logistique & Portuaire",
    city: "Pointe-Noire",
    address: "Terminal à Conteneurs du Port Autonome de Pointe-Noire",
    description: "Gestion d'infrastructures portuaires et opérations logistiques de pointe.",
    phone: "+242 22 294 02 10",
    email: "contact.congo@aglgroup.com",
    website: "https://www.aglgroup.com",
  },
];

export const initialEnglishClubs: AnnuaireItem[] = [
  {
    id: "brazza-english-club",
    name: "Brazzaville English Practice Club",
    city: "Brazzaville",
    location: "Centre Culturel Russe / Poto-Poto, Brazzaville",
    schedule: "Chaque samedi de 15h00 à 17h30",
    coordinator: "Coach Steve & Team",
    phone: "+242 06 820 44 11",
    description:
      "Club d'échange ouvert aux étudiants et jeunes professionnels pour débloquer l'expression orale et préparer des entretiens en anglais.",
    fee: "Gratuit / Contribution symbolique",
  },
  {
    id: "american-corner-umng",
    name: "American Corner English Club (UMNG)",
    city: "Brazzaville",
    location: "Bibliothèque Universitaire Centrale UMNG, Brazzaville",
    schedule: "Mercredi et Vendredi à 14h00",
    coordinator: "Centre Culturel Américain",
    phone: "+242 06 612 00 00",
    description: "Ateliers de conversation, projections en version originale et préparation aux tests TOEFL/IELTS.",
    fee: "100% Gratuit",
  },
  {
    id: "pn-toastmasters-english",
    name: "Pointe-Noire English Speakers Forum",
    city: "Pointe-Noire",
    location: "Quartier Lumumba, près du rond-point Kassaï",
    schedule: "Chaque dimanche de 16h00 à 18h00",
    coordinator: "M. Patrick M.",
    phone: "+242 05 522 90 80",
    description: "Développement du leadership et prise de parole en public en langue anglaise pour les jeunes diplômés.",
    fee: "Adhésion libre",
  },
];
